/**
 * Mock recommendation profiles used during onboarding step 3.
 *
 * 12 startups + 12 investors, each fully populated. Every profile is
 * distinct on sector, stage, geography, and tone so the placeholder
 * ranking has signal to work with.
 *
 * Logos are NOT image URLs — the UI renders an Avatar with deterministic
 * initials + colour from `lib/profile/avatar.ts`. This keeps the demo
 * stable (no broken images, no CDN dependency).
 *
 * This file is mock-only. It must not leak into production matching,
 * feed, or analytics paths.
 */

import type {
  InvestorRecommendation,
  StartupRecommendation,
} from "./types";

// ─────────────────────────────────────────────────────────────────────────────
//  Startups (12) — what investors see during onboarding
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_STARTUPS: StartupRecommendation[] = [
  {
    kind: "startup",
    id: "mock-startup-01",
    name: "Lattice Forge",
    tagline: "Code-aware CI that explains every red build in plain English.",
    description:
      "Lattice Forge sits between GitHub Actions and your team's chat tool. When a build fails it traces the error to the changed lines, summarises the diff in plain English, and posts a fix-or-revert recommendation back to the PR within seconds.",
    sector: "Developer tools",
    stage: "seed",
    location: "San Francisco, CA",
    foundingYear: 2024,
    websitePlaceholder: "latticeforge.example",
    tags: ["devtools", "ci-cd", "ai", "developer-experience", "github"],
    customerType: "developer",
    founder: {
      fullName: "Sana Okafor",
      role: "CEO",
      workEmail: "sana@latticeforge.example",
      linkedinUrl: "https://linkedin.com/in/sanaokafor",
      photoUrl: "/mock-assets/lattice-forge/sana-okafor.png",
    },
    website: "https://latticeforge.example",
    productStatus: "launched",
    traction:
      "1,400 weekly active repos, $32K MRR, three Series-B customers in pilot (Notion, Linear, ClickUp).",
    mrr: "$32K",
    customers: "1,400 weekly active repos across 200+ teams",
    growthPct: "22% MoM",
    notableSignals: "Three Series-B companies (Notion, Linear, ClickUp) in pilot",
    fundingAsk: "$2.5M seed",
    useOfFunds:
      "Hire two senior engineers, pay for OpenAI inference at scale, and run a six-month enterprise pilot programme.",
    instrument: "SAFE",
    valuationCap: "$15M",
    minCheckSize: "$100K",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
    teamMembers: [
      { name: "Sana Okafor", role: "CEO", background: "Former developer-experience lead at Vercel. Shipped v0 onboarding.", photoUrl: "/mock-assets/lattice-forge/sana-okafor.png" },
      { name: "Tomás Rivera", role: "CTO", background: "Led the GitHub Actions runtime team for four years.", photoUrl: "/mock-assets/lattice-forge/tomas-rivera.png" },
      { name: "Priya Nair", role: "Head of ML", background: "Research engineer at DeepMind, focused on code understanding.", photoUrl: "/mock-assets/lattice-forge/priya-nair.png" },
    ],
    advisors: ["Former VP Engineering at CircleCI", "Head of DevRel at Vercel"],
    founderSummary:
      "Two ex-GitHub engineers. CTO led the Actions runtime team for four years; CEO ran developer experience at Vercel and shipped the v0 onboarding.",
    problemStatement: "When CI builds fail, developers waste 30+ minutes deciphering cryptic error logs and tracing which lines broke the build.",
    targetCustomer: "Engineering teams at 10-500 person companies using GitHub Actions for CI/CD",
    currentAlternatives: "Manual log reading, Codecov for coverage only, BuildPulse for flaky tests",
    whyAlternativesFail: "No existing tool explains build failures in plain English or suggests fixes inline in the PR",
    product:
      "GitHub App + CLI. Hooks into existing workflows with a one-line YAML change. Free for open source.",
    keyFeatures: "Plain-English build-failure explanations, fix-or-revert PR recommendations, one-line YAML install",
    technicalMoat: "Proprietary diff-tracing engine trained on 2M+ CI failure patterns across open-source repos",
    roadmap: "Enterprise tier with SOC 2 (Q3 2026), GitLab and Bitbucket support (Q1 2027), auto-fix mode (Q2 2027)",
    targetMarket: "Engineering teams at companies with 10-500 developers using GitHub Actions or similar CI systems.",
    marketSize: "$4.2B CI/CD market, growing 18% YoY. Addressable segment: $800M in build-intelligence tooling.",
    marketTrend: "CI/CD market growing 18% YoY; AI-assisted developer tools seeing 3x adoption growth",
    beachheadMarket: "Open-source maintainers and mid-stage startups on GitHub Actions",
    whyNow: "LLMs can finally parse and explain code diffs in natural language. GitHub Actions dominance creates a single integration point.",
    competitors: ["Codecov (coverage only)", "BuildPulse (flaky test detection)", "Trunk.io (merge queues)"],
    differentiation: "Only tool that explains failures in plain English and suggests fix-or-revert in the PR itself. One-line YAML install.",
    whyWeWin: "First-mover in AI build explanation, viral open-source adoption loop, one-line install removes all friction",
    defensibility: "Network effects from 2M+ failure patterns, open-source community lock-in, deep GitHub integration",
    businessModel: "Freemium SaaS. Free for open-source repos, $49/seat/month for teams, enterprise custom.",
    revenueModel: "Seat-based subscription with usage tiers for inference volume.",
    pricing: "Free for open-source, $49/seat/month for teams, custom enterprise pricing",
    grossMargin: "~72% (inference costs are the main COGS driver)",
    salesCycle: "Self-serve for teams (same-day), enterprise 4-8 weeks",
    gtmStrategy: "Product-led growth via open-source adoption, then team-plan upsell. Conference talks and DevRel content.",
    plannedGtm: "Product-led growth through GitHub Marketplace and open-source adoption, then enterprise outbound",
    acquisitionChannels: ["GitHub Marketplace", "Developer conferences", "Technical blog content", "Open-source community"],
    risks: ["OpenAI inference costs could spike if token volume grows faster than pricing", "GitHub could build native build-explanation features", "Enterprise sales cycle may be longer than expected"],
    biggestUnknown: "Whether enterprise buyers will pay a premium for build intelligence or treat it as a nice-to-have",
    failureScenario: "GitHub ships native AI build explanation in Actions, commoditizing the core feature",
    idealInvestor:
      "Devtools-native investor who has shipped CI or developer-experience products before. Bonus if they know enterprise sales motions.",
    milestonesAfterRaise: ["100K weekly active repos", "Launch enterprise tier with SOC 2", "Expand beyond GitHub to GitLab and Bitbucket"],
    capTable: { totalRaised: "$500K (friends & family)", founderEquity: "82%", optionPool: "10%" },
    notableCustomers: "Notion, Linear, and ClickUp in pilot; 200+ open-source projects including three top-100 GitHub repos",
    customerProof: "84% of pilot users report saving 30+ minutes per failed build; NPS of 72 among paying teams",
    retentionEngagement: "93% monthly retention; average team runs 4,200 builds/month through Lattice Forge",
  },
  {
    kind: "startup",
    id: "mock-startup-02",
    name: "Marrow Health",
    tagline: "Bone-marrow donor matching for the 70% of patients who never find one.",
    description:
      "Marrow Health builds a federated registry that lets transplant centres share donor matches across hospital networks without moving identifiable PHI. We focus on improving match rates for African American, Latino, and multiracial patients who are systematically under-represented in existing registries.",
    sector: "Healthcare",
    stage: "seed",
    location: "Boston, MA",
    foundingYear: 2023,
    websitePlaceholder: "marrowhealth.example",
    tags: ["healthcare", "biotech", "clinical-software", "health-equity", "regulated"],
    customerType: "enterprise",
    founder: {
      fullName: "Dr. Amina Okoro",
      role: "CEO",
      workEmail: "amina@marrowhealth.example",
      linkedinUrl: "https://linkedin.com/in/aminaokoro",
      photoUrl: "/mock-assets/marrow-health/amina-okoro.png",
    },
    website: "https://marrowhealth.example",
    productStatus: "beta",
    traction:
      "Increased multiracial-patient match rates by 41% in pilot. LOIs from four transplant networks representing 11 hospitals.",
    mrr: "$18K",
    customers: "2 transplant centres live, 4 more in LOI",
    growthPct: "15% MoM",
    notableSignals: "41% improvement in multiracial-patient match rates in pilot",
    fundingAsk: "$4M seed",
    useOfFunds:
      "Clinical validation study, two more transplant-centre integrations, and a regulatory affairs hire to push toward broader registry adoption.",
    instrument: "Priced equity",
    valuationCap: "$20M",
    minCheckSize: "$250K",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
    teamMembers: [
      { name: "Dr. Amina Okoro", role: "CEO", background: "Hematologist-oncologist, 8 years at Dana-Farber Cancer Institute.", photoUrl: "/mock-assets/marrow-health/amina-okoro.png" },
      { name: "James Liao", role: "CTO", background: "Built clinical data infrastructure at Stripe Health (pre-spin). Led HIPAA-compliant data pipelines.", photoUrl: "/mock-assets/marrow-health/james-liao.png" },
      { name: "Dr. Kareem Washington", role: "Chief Medical Officer", background: "Former head of bone-marrow transplant at MD Anderson. Advisor at Anthropic on health AI.", photoUrl: "/mock-assets/marrow-health/kareem-washington.png" },
    ],
    advisors: ["Head of transplant at MD Anderson", "Former CISO of a top-3 US health system"],
    founderSummary:
      "CEO is a hematologist-oncologist from Dana-Farber. CTO built infrastructure at Flatiron Health. Clinical advisory board includes the head of bone-marrow transplant at MD Anderson.",
    problemStatement: "70% of patients who need a bone-marrow transplant never find a matching donor because registries are siloed and under-represent minority populations.",
    targetCustomer: "Transplant programme directors at academic medical centres and large hospital networks",
    currentAlternatives: "Be The Match (siloed registry), DKMS (international only), hospital-specific internal registries",
    whyAlternativesFail: "Existing registries cannot query across networks without moving PHI, and systematically under-represent minority patients",
    product:
      "HIPAA-compliant federated query layer plus a clinician-facing match dashboard. Live in two transplant centres.",
    keyFeatures: "Federated cross-network donor matching, HIPAA-compliant query layer, clinician-facing match dashboard",
    technicalMoat: "Privacy-preserving federated compute architecture that enables cross-hospital queries without moving identifiable data",
    roadmap: "10 transplant centres by Q4 2026, peer-reviewed clinical validation study (Q1 2027), UK/Canada expansion (Q3 2027)",
    targetMarket: "130+ transplant centres in the US, plus international registries in Canada and the UK.",
    marketSize: "$2.8B transplant services market. Addressable: $400M in registry and matching software.",
    marketTrend: "Privacy-preserving federated compute maturing rapidly; health-equity mandates driving hospital purchasing",
    beachheadMarket: "US academic transplant centres with active bone-marrow programmes serving diverse patient populations",
    whyNow: "Privacy-preserving federated compute is now mature enough to query across hospital networks without moving PHI.",
    competitors: ["Be The Match (nonprofit registry)", "DKMS (international)", "Hospital-specific internal registries"],
    differentiation: "Federated architecture queries across all registries simultaneously without moving identifiable data. Purpose-built for under-represented populations.",
    whyWeWin: "Only federated solution purpose-built for transplant matching; clinical outcomes data no competitor has",
    defensibility: "Network effects — each additional hospital increases match rates for all participants, creating a growing data moat",
    businessModel: "SaaS licensing per transplant centre plus per-query fees for cross-network searches.",
    revenueModel: "Annual contracts with transplant centres, $80-150K per centre.",
    pricing: "$80-150K annual contract per transplant centre plus per-query fees for cross-network searches",
    grossMargin: "~85% (software-only, no lab costs)",
    salesCycle: "12-18 months (hospital procurement)",
    gtmStrategy: "Clinical champion model: win one transplant director per network, expand to the rest of the system.",
    plannedGtm: "Clinical champion model: convert one transplant director per network, expand to the rest of the system",
    acquisitionChannels: ["Transplant-centre partnerships", "Clinical conferences (ASH, ASBMT)", "Published clinical outcomes"],
    risks: ["Regulatory complexity across state privacy laws", "Slow hospital procurement cycles (12-18 months)", "Dependence on clinical-champion buy-in"],
    biggestUnknown: "Whether hospital procurement committees will approve a novel federated architecture for clinical-grade matching",
    failureScenario: "Major registry (Be The Match) builds federated capability in-house, leveraging existing hospital relationships",
    idealInvestor:
      "Healthcare-focused investor with a track record in clinical software, FDA strategy, or hospital go-to-market.",
    milestonesAfterRaise: ["10 transplant centres live", "Published peer-reviewed clinical validation", "Expand to UK/Canada registries"],
    capTable: { totalRaised: "$750K (pre-seed)", founderEquity: "78%", optionPool: "12%" },
    notableCustomers: "Dana-Farber Cancer Institute and Massachusetts General Hospital (pilot sites)",
    customerProof: "41% improvement in multiracial match rates; transplant directors describe it as 'the first real innovation in matching in 20 years'",
    retentionEngagement: "100% pilot retention; average 85 cross-network queries per centre per month",
  },
  {
    kind: "startup",
    id: "mock-startup-03",
    name: "Quill & Ledger",
    tagline: "AI bookkeeping for venture-backed startups under 50 employees.",
    description:
      "Quill & Ledger replaces the manual transaction-tagging work that bookkeepers do for every venture-backed startup. The AI ingests bank feeds, AWS invoices, and Stripe payouts, classifies each transaction against the company's chart of accounts, and produces investor-ready monthly close packets in 48 hours.",
    sector: "Fintech",
    stage: "pre_seed",
    location: "New York, NY",
    foundingYear: 2024,
    websitePlaceholder: "quillandledger.example",
    tags: ["fintech", "ai", "saas", "accounting", "bookkeeping", "b2b"],
    customerType: "smb",
    founder: {
      fullName: "Corinne Dupont",
      role: "CEO",
      workEmail: "corinne@quillandledger.example",
      linkedinUrl: "https://linkedin.com/in/corinnedupont",
      photoUrl: "/mock-assets/quill-and-ledger/corinne-dupont.png",
    },
    website: "https://quillandledger.example",
    productStatus: "beta",
    traction:
      "27 paying companies, $19K MRR, 84% of pilots converted to paid after the first close cycle.",
    mrr: "$19K",
    customers: "27 paying companies",
    growthPct: "18% MoM",
    notableSignals: "84% pilot-to-paid conversion rate after first close cycle",
    fundingAsk: "$1.2M pre-seed",
    useOfFunds:
      "Build out the audit-trail product, hire one ML engineer, and add Rippling and Mercury integrations.",
    instrument: "SAFE",
    valuationCap: "$8M",
    minCheckSize: "$50K",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
    teamMembers: [
      { name: "Corinne Dupont", role: "CEO", background: "Ran the controller-tools team at Stripe. Built internal AP automation used across 200+ business accounts.", photoUrl: "/mock-assets/quill-and-ledger/corinne-dupont.png" },
      { name: "Riku Tanaka", role: "CTO", background: "Led AI engineering at Notion. Two patents in structured-data extraction and classification.", photoUrl: "/mock-assets/quill-and-ledger/riku-tanaka.png" },
      { name: "Anisha Gupta", role: "Head of Integrations", background: "Staff engineer at Stripe, built the ledger-sync and Radar fraud APIs.", photoUrl: "/mock-assets/quill-and-ledger/anisha-gupta.png" },
    ],
    advisors: ["CFO of a top-20 YC company", "Former VP Product at Xero"],
    founderSummary:
      "Founders met at Brex — one ran the controller-tools team, the other ran AI at Pilot. Two technical hires from Plaid.",
    problemStatement: "Venture-backed startups under 50 employees waste 20+ hours per month on manual transaction tagging and reconciliation.",
    targetCustomer: "Venture-backed startups with 5-50 employees and no dedicated controller or CFO",
    currentAlternatives: "Pilot (human bookkeepers), Bench (sunset), manual bookkeeper + QuickBooks",
    whyAlternativesFail: "Human-in-the-loop bookkeeping is slow (2+ weeks for monthly close) and expensive ($500-2,000/month)",
    product:
      "Closed-beta web app, integrations with QuickBooks Online and Xero, Slack-based monthly review.",
    keyFeatures: "AI transaction classification at 95%+ accuracy, investor-ready monthly close packets in 48 hours, Slack-based review workflow",
    technicalMoat: "Proprietary transaction-classification model trained on 500K+ startup transactions with chart-of-accounts context",
    roadmap: "Rippling and Mercury integrations (Q3 2026), SOC 2 Type II (Q4 2026), multi-entity support (Q1 2027)",
    targetMarket: "50,000+ venture-backed startups in the US with less than 50 employees and no dedicated controller.",
    marketSize: "$12B SMB accounting-software market. Addressable: $1.5B in AI-assisted bookkeeping.",
    marketTrend: "LLM accuracy for financial data crossing the threshold for production use; startup ecosystem rebounding",
    beachheadMarket: "YC and top-accelerator alumni companies with Stripe + Mercury as primary financial stack",
    whyNow: "LLMs can now classify transactions with 95%+ accuracy. Plaid and Mercury APIs make bank-feed ingestion trivial.",
    competitors: ["Pilot (human bookkeepers + software)", "Bench (acquired, sunset)", "Finta (fundraising-focused)"],
    differentiation: "Fully automated — no human bookkeeper in the loop. Investor-ready monthly close packets in 48 hours vs. 2 weeks.",
    whyWeWin: "Fastest monthly close in the market (48 hours vs. 2 weeks), zero human bookkeeper overhead, built by ex-Brex and ex-Pilot team",
    defensibility: "Compounding accuracy advantage — each customer's transactions improve the classification model for all",
    businessModel: "Monthly SaaS subscription, tiered by transaction volume.",
    revenueModel: "$99/month for startups <$1M revenue, $249/month for $1-5M, enterprise custom.",
    pricing: "$99/month for startups under $1M revenue, $249/month for $1-5M, enterprise custom",
    grossMargin: "~78%",
    salesCycle: "Self-serve signup, 14-day free trial, conversion within first close cycle (30 days)",
    gtmStrategy: "Partner with startup banks (Mercury, Brex) for embedded distribution. Content marketing to CFO/controller persona.",
    plannedGtm: "Embedded distribution through Mercury and Brex partnerships, YC batch deals, founder community content",
    acquisitionChannels: ["Mercury and Brex partnerships", "YC batch distribution", "Founder communities (Twitter, newsletters)"],
    risks: ["QuickBooks or Xero could build native AI classification", "Accuracy failures could erode trust quickly", "Switching costs are low for early-stage companies"],
    biggestUnknown: "Whether founders will trust AI with their books without a human backstop",
    failureScenario: "QuickBooks or Xero ships native AI classification, removing the need for a standalone product",
    idealInvestor:
      "Fintech-savvy investor who understands the controller persona, comfortable with B2B SaaS economics, and willing to write a $250-500K check.",
    milestonesAfterRaise: ["200 paying companies", "Launch Rippling and Mercury integrations", "SOC 2 Type II certification"],
    capTable: { totalRaised: "$300K (pre-seed from angels)", founderEquity: "85%", optionPool: "10%" },
    notableCustomers: "Three YC W24 companies and two Techstars NYC alumni",
    customerProof: "84% pilot-to-paid conversion; average close-time reduction from 14 days to 2 days",
    retentionEngagement: "91% monthly retention; 97% of transactions auto-classified without manual override",
  },
  {
    kind: "startup",
    id: "mock-startup-04",
    name: "Polestar Climate",
    tagline: "Industrial heat pumps that retire factory steam boilers.",
    description:
      "Polestar Climate designs high-temperature industrial heat pumps that replace gas-fired steam boilers in food-and-beverage and chemical plants. We deliver 180°C process heat at 4x the efficiency of gas, paying back the capex in under three years at current US energy prices.",
    sector: "Climate",
    stage: "series_a",
    location: "Berkeley, CA",
    foundingYear: 2022,
    websitePlaceholder: "polestarclimate.example",
    tags: ["climate", "hardware", "industrial", "decarbonisation", "ira", "deeptech"],
    customerType: "enterprise",
    founder: {
      fullName: "Sofia Engström",
      role: "CEO",
      workEmail: "sofia@polestarclimate.example",
      linkedinUrl: "https://linkedin.com/in/sofiaengstrom",
      photoUrl: "/mock-assets/polestar-climate/sofia-engstrom.png",
    },
    website: "https://polestarclimate.example",
    productStatus: "revenue_generating",
    traction:
      "$1.1M in signed pilots, $14M of LOIs from prospective customers, IRA-aligned tax credits secured.",
    mrr: "$92K",
    customers: "2 field trials active, $14M in LOIs from 8 prospective customers",
    growthPct: "35% QoQ",
    notableSignals: "IRA-aligned tax credits secured; DOE expressed interest in demonstration programme",
    fundingAsk: "$18M Series A",
    useOfFunds:
      "Build a contract-manufacturing line in Reno, deploy 12 commercial units in 2026, hire an industrial-sales team.",
    instrument: "Priced equity",
    valuationCap: "$75M pre-money",
    minCheckSize: "$1M",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
    teamMembers: [
      { name: "Sofia Engström", role: "CEO", background: "Led heat-pump programme at a cleantech company backed by Khosla Ventures. 3 patents in industrial thermal systems.", photoUrl: "/mock-assets/polestar-climate/sofia-engstrom.png" },
      { name: "Dr. Wei Chen", role: "VP Engineering", background: "PhD Stanford ME, two patents in high-temperature heat-pump design. Previously at Vercel as a research partner.", photoUrl: "/mock-assets/polestar-climate/wei-chen.png" },
      { name: "Marcus Holt", role: "COO", background: "Former VP Operations at a Founders Fund portfolio company. Scaled manufacturing to 3 countries.", photoUrl: "/mock-assets/polestar-climate/marcus-holt.png" },
    ],
    advisors: ["Former DOE Under Secretary for Energy", "VP Manufacturing at Carrier Global"],
    founderSummary:
      "CEO came from Tesla's heat-pump programme. Two PhDs from Stanford ME on the founding team. Hardware leadership from a previous defence-tech exit.",
    problemStatement: "Industrial process heat accounts for 10% of global CO₂ emissions. Gas-fired steam boilers dominate because electric alternatives couldn't reach 180°C until now.",
    targetCustomer: "Plant engineers and facilities managers at food-and-beverage and chemical processing plants spending $50K+/year on natural gas",
    currentAlternatives: "Gas-fired steam boilers (Cleaver-Brooks), EU residential heat pumps (Neatpump), thermal storage (Kraftblock)",
    whyAlternativesFail: "No electric alternative could reach 180°C process heat at industrial scale until now; thermal storage does not replace the heat source",
    product:
      "200kW industrial heat-pump module. Two units in field trial at a craft brewery and a dairy processor.",
    keyFeatures: "180°C process heat output, 4x gas efficiency, under 3-year capex payback, IRA tax-credit eligible",
    technicalMoat: "Two patents on high-temperature compressor design; proprietary refrigerant blend enabling 180°C output",
    roadmap: "Contract manufacturing line in Reno (Q3 2026), 12 commercial deployments (Q4 2026), chemical-plant product variant (Q2 2027)",
    targetMarket: "Food-and-beverage plants and chemical facilities in the US that spend $50K+/year on natural gas.",
    marketSize: "$28B industrial heating market. Addressable: $6B in retrofit heat-pump opportunities.",
    marketTrend: "Natural gas prices doubled since 2020; IRA creating $369B in climate incentives; industrial decarbonisation mandates accelerating",
    beachheadMarket: "Craft breweries and dairy processors in California and the Pacific Northwest",
    whyNow: "IRA tax credits cover 30-50% of capex. Natural gas prices have doubled since 2020. New compressor tech enables 180°C output.",
    competitors: ["Traditional gas-boiler manufacturers (Cleaver-Brooks)", "Neatpump (EU, residential focus)", "Kraftblock (thermal storage, not heat pumps)"],
    differentiation: "Only industrial heat pump delivering 180°C at 200kW scale. 3-year payback at current energy prices.",
    whyWeWin: "Only 180°C industrial heat pump at 200kW scale; 3-year payback makes the business case undeniable even without climate mandates",
    defensibility: "Patent-protected compressor design, 18-month hardware lead over nearest competitor, IRA incentive expertise",
    businessModel: "Hardware sales plus 5-year service contracts. IRA pass-through reduces customer capex by 30-50%.",
    revenueModel: "Unit sales ($150-300K per module) + annual maintenance contracts ($15-25K).",
    pricing: "$150-300K per 200kW module, plus $15-25K annual maintenance contracts",
    grossMargin: "~45% on hardware, ~75% on service contracts",
    salesCycle: "6-12 months for enterprise; 3-6 months for food-and-beverage",
    gtmStrategy: "Direct sales to plant engineers. First land in food-and-beverage (shorter sales cycles), then expand to chemicals.",
    plannedGtm: "Direct sales to plant engineers via industry trade shows and energy-audit partnerships; DOE demonstration programmes as credibility accelerant",
    acquisitionChannels: ["Industry trade shows (IIAR, ASHRAE)", "Energy-audit partnerships", "DOE demonstration programmes"],
    risks: ["Manufacturing scale-up risk with contract manufacturer", "Long enterprise sales cycles (6-12 months)", "Compressor supply chain concentration"],
    biggestUnknown: "Whether contract manufacturing can deliver consistent quality at the target cost for the first 50 units",
    failureScenario: "Compressor supply chain disruption delays production by 6+ months, causing LOI customers to choose gas-boiler replacements instead",
    idealInvestor:
      "Climate-tech-native lead investor who has scaled hardware before and is comfortable with manufacturing capex and IRA dynamics.",
    milestonesAfterRaise: ["12 commercial units deployed", "Contract manufacturing line operational in Reno", "Achieve $8M ARR from service contracts"],
    capTable: { totalRaised: "$4.5M (seed)", founderEquity: "68%", optionPool: "12%" },
    notableCustomers: "Bay Area craft brewery (pilot) and a regional dairy processor (pilot); LOIs from two Fortune 500 food companies",
    customerProof: "Pilot customers report 62% reduction in energy costs for process heat; zero unplanned downtime in 6 months of field trials",
    retentionEngagement: "100% pilot retention; both pilot customers have submitted expansion orders for additional modules",
  },
  {
    kind: "startup",
    id: "mock-startup-05",
    name: "Glyph",
    tagline: "On-device AI for clinical-grade hearing aids at $400 instead of $4,000.",
    description:
      "Glyph is a sub-$500 hearing aid that runs noise-suppression and speech-isolation models on a custom DSP chip. It targets the 28 million Americans with mild-to-moderate hearing loss who can't justify the cost of premium devices today.",
    sector: "Hardware",
    stage: "seed",
    location: "Austin, TX",
    foundingYear: 2023,
    websitePlaceholder: "glyph.example",
    tags: ["hardware", "consumer-health", "audio", "ai", "fda"],
    customerType: "consumer",
    founder: {
      fullName: "Dara Osei",
      role: "CEO",
      workEmail: "dara@glyph.example",
      linkedinUrl: "https://linkedin.com/in/daraosei",
      photoUrl: "/mock-assets/glyph/dara-osei.png",
    },
    website: "https://glyph.example",
    productStatus: "prototype",
    traction:
      "12,000 person waiting list, $1.4M in pre-orders, two retail-distribution LOIs.",
    mrr: "$0 (pre-revenue; $1.4M in pre-orders)",
    customers: "12,000 person waiting list, $1.4M in pre-orders",
    growthPct: "1,200 new waitlist signups per month (28% MoM growth)",
    notableSignals: "Two retail-distribution LOIs from major pharmacy chains (CVS, Walgreens)",
    fundingAsk: "$3M seed",
    useOfFunds:
      "Finish FDA paperwork, build initial 5,000-unit production run with a Taiwan ODM partner, hire two acoustic engineers.",
    instrument: "SAFE",
    valuationCap: "$18M",
    minCheckSize: "$100K",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
    teamMembers: [
      { name: "Dara Osei", role: "CEO", background: "Former firmware lead at Bose Hearphones. 12 years in audio hardware.", photoUrl: "/mock-assets/glyph/dara-osei.png" },
      { name: "Kevin Park", role: "CTO", background: "Audio-DSP lead on Slack Huddles. 8 patents in real-time noise suppression and spatial audio.", photoUrl: "/mock-assets/glyph/kevin-park.png" },
      { name: "Dr. Lisa Fontaine", role: "Clinical Advisor", background: "Past president of the American Academy of Audiology. Research partner at Anthropic on hearing accessibility.", photoUrl: "/mock-assets/glyph/lisa-fontaine.png" },
    ],
    advisors: ["Former VP Hardware at Sonos", "FDA regulatory consultant (ex-Medtronic)"],
    founderSummary:
      "CEO previously led firmware at Bose Hearphones. CTO is the audio-DSP lead from a major Pixel Buds programme. Clinical advisor is past president of the AAA.",
    problemStatement: "28 million Americans with mild-to-moderate hearing loss can't justify $4,000+ for premium hearing aids, leaving them untreated.",
    targetCustomer: "Adults aged 40-70 with mild-to-moderate hearing loss who are price-sensitive and tech-comfortable",
    currentAlternatives: "Premium hearing aids ($4,000+), Jabra Enhance (limited AI), Sony CRE-C10 (no clinical features), Eargo (bankrupt)",
    whyAlternativesFail: "Premium aids are too expensive for most; OTC alternatives lack clinical-grade noise suppression and speech isolation",
    product:
      "First-generation hearing aid with companion iOS/Android app. FDA OTC clearance in progress.",
    keyFeatures: "On-device clinical-grade noise suppression, speech isolation via custom DSP, companion app with audiologist telehealth",
    technicalMoat: "Custom DSP chip running proprietary noise-suppression models; 8 patents from CTO's Google audio work",
    roadmap: "FDA OTC clearance (Q3 2026), 5,000-unit first production run (Q4 2026), Amazon and CVS launch (Q1 2027)",
    targetMarket: "Adults 40-70 with mild-to-moderate hearing loss in the US. Secondary: international OTC markets.",
    marketSize: "$11B global hearing-aid market. Addressable: $3.2B OTC segment (post-FDA ruling).",
    marketTrend: "FDA OTC ruling opened the market in 2022; 28M Americans with untreated hearing loss; ageing population accelerating demand",
    beachheadMarket: "Tech-forward adults 40-55 with mild hearing loss who already use Bluetooth earbuds",
    whyNow: "FDA OTC hearing-aid ruling (2022) opened the market. On-device AI can now run clinical-grade noise suppression on a $15 chip.",
    competitors: ["Jabra Enhance (Bluetooth, limited AI)", "Sony CRE-C10 (good sound, no clinical features)", "Eargo (DTC, filed for bankruptcy)"],
    differentiation: "Clinical-grade noise suppression and speech isolation on a custom DSP at 1/10th the price of traditional aids.",
    whyWeWin: "10x price advantage over premium aids with clinical-grade audio quality; first OTC device with on-device AI speech isolation",
    defensibility: "8 patents on DSP-based noise suppression; custom chip design with 18-month hardware lead; audiologist telehealth network",
    businessModel: "Direct-to-consumer hardware sales plus optional subscription for AI model updates and audiologist telehealth.",
    revenueModel: "$399 per device, $9.99/month premium subscription for advanced features.",
    pricing: "$399 per device, $9.99/month optional premium subscription for AI updates and telehealth",
    grossMargin: "~55% on hardware, ~90% on subscription",
    salesCycle: "Direct-to-consumer: instant online purchase; retail: 4-6 week shelf placement cycle",
    gtmStrategy: "DTC via website and Amazon. Retail distribution through pharmacy chains (CVS, Walgreens LOIs signed).",
    plannedGtm: "DTC website and Amazon for initial launch; CVS and Walgreens retail distribution; audiologist referral programme",
    acquisitionChannels: ["DTC website", "Amazon", "CVS and Walgreens retail", "Audiologist referrals"],
    risks: ["FDA OTC clearance timeline uncertainty", "Consumer trust in sub-$500 hearing aids", "Apple could enter with AirPods-as-hearing-aid"],
    biggestUnknown: "FDA OTC clearance timeline — a delay could push the production run back by two quarters",
    failureScenario: "Apple launches clinical-grade hearing features in AirPods Pro, capturing the tech-forward segment at a lower price point",
    idealInvestor:
      "Hardware-friendly seed investor who has shipped consumer electronics or medical devices before.",
    milestonesAfterRaise: ["FDA OTC clearance", "5,000-unit first production run", "Launch on Amazon and CVS"],
    capTable: { totalRaised: "$800K (friends & family + angel)", founderEquity: "80%", optionPool: "10%" },
    notableCustomers: "12,000 waitlist signups; pre-order customers include three audiologists and a retired ENT surgeon who want the product for personal use",
    customerProof: "Prototype testers report 'life-changing' clarity in noisy environments; 94% of beta testers say they would recommend to a friend",
    retentionEngagement: "Beta programme: 97% daily usage rate; average 14 hours/day wear time among active testers",
  },
  {
    kind: "startup",
    id: "mock-startup-06",
    name: "Steeple Markets",
    tagline: "Liquidity for the $32B private-credit secondaries market.",
    description:
      "Steeple Markets runs a regulated marketplace where institutional holders of private-credit funds can sell their positions to qualified buyers. We turn what is today a relationship-driven, six-week process into a multi-day RFQ with transparent pricing.",
    sector: "Fintech",
    stage: "seed",
    location: "New York, NY",
    foundingYear: 2024,
    websitePlaceholder: "steeplemarkets.example",
    tags: ["fintech", "capital-markets", "secondaries", "regulated", "b2b"],
    customerType: "enterprise",
    founder: {
      fullName: "Rachel Whitmore",
      role: "CEO",
      workEmail: "rachel@steeplemarkets.example",
      linkedinUrl: "https://linkedin.com/in/rachelwhitmore",
      photoUrl: "/mock-assets/steeple-markets/rachel-whitmore.png",
    },
    website: "https://steeplemarkets.example",
    productStatus: "launched",
    traction:
      "Eight institutional buyers onboarded. First three trades closed at a combined $42M notional.",
    mrr: "$35K",
    customers: "8 institutional buyers onboarded",
    growthPct: "40% MoM in trading volume",
    notableSignals: "First three trades closed at $42M combined notional; FINRA engagement on ATS application",
    fundingAsk: "$5M seed",
    useOfFunds:
      "Hire two FIX-protocol engineers, expand compliance team, and pursue ATS approval.",
    instrument: "SAFE",
    valuationCap: "$25M",
    minCheckSize: "$200K",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
    teamMembers: [
      { name: "Rachel Whitmore", role: "CEO", background: "Ran private-credit secondaries desk at Goldman Sachs for 6 years. Backed by Sequoia in prior fintech venture.", photoUrl: "/mock-assets/steeple-markets/rachel-whitmore.png" },
      { name: "Amir Patel", role: "CTO", background: "Capital-markets infrastructure exit (sold to ICE). Built FIX-protocol systems, previously at Stripe Capital.", photoUrl: "/mock-assets/steeple-markets/amir-patel.png" },
      { name: "Diane Kowalski", role: "Chief Compliance Officer", background: "Former SEC enforcement attorney, 15 years in broker-dealer compliance.", photoUrl: "/mock-assets/steeple-markets/diane-kowalski.png" },
    ],
    advisors: ["Former FINRA board member", "Head of alternatives at a top-10 US pension fund"],
    founderSummary:
      "CEO ran private-credit secondaries at Goldman. CTO came from an exit in capital-markets infrastructure. Compliance lead from the SEC.",
    problemStatement: "Private-credit fund holders who want liquidity face a 6-week, relationship-driven process with zero price transparency.",
    targetCustomer: "Institutional holders of private-credit fund positions — pension funds, endowments, and insurance companies seeking liquidity",
    currentAlternatives: "Lazard (advisory, 6-week process), Jefferies (block trades, relationship-driven), ad-hoc broker networks",
    whyAlternativesFail: "Existing process takes 6+ weeks, relies on personal relationships, and offers zero price transparency",
    product:
      "FINRA-licensed RFQ platform with audit logs, stress-test reporting, and full KYC/AML.",
    keyFeatures: "Multi-day RFQ execution, transparent pricing with audit trails, full KYC/AML and stress-test reporting",
    technicalMoat: "FINRA-licensed platform with proprietary RFQ matching engine; compliance infrastructure built for regulated secondaries",
    roadmap: "ATS approval (Q4 2026), 20 institutional buyers (Q1 2027), European expansion under MiFID II (Q3 2027)",
    targetMarket: "Institutional holders of private-credit fund positions — pension funds, endowments, insurance companies.",
    marketSize: "$32B private-credit secondaries market, growing 25% YoY as private credit AUM expands.",
    marketTrend: "Private credit AUM tripled since 2019; institutional demand for liquidity far outpacing existing broker capacity",
    beachheadMarket: "US pension funds and endowments with $100M+ in private-credit allocations seeking near-term liquidity",
    whyNow: "Private credit AUM has tripled since 2019. Institutional demand for liquidity is outpacing existing broker networks.",
    competitors: ["Lazard (advisory)", "Jefferies (block trades)", "CAIS (alternatives platform, different focus)"],
    differentiation: "First regulated RFQ marketplace purpose-built for private-credit secondaries. Multi-day execution vs. 6 weeks.",
    whyWeWin: "First regulated RFQ marketplace for private-credit secondaries; execution in days vs. weeks; Goldman-pedigree team",
    defensibility: "Regulatory moat (FINRA licence + ATS pending), network effects from buyer-seller liquidity, proprietary pricing data",
    businessModel: "Transaction fees on completed trades (25-50bps). No subscription fees.",
    revenueModel: "Per-trade fee, 25-50bps on notional value.",
    pricing: "25-50bps transaction fee on completed trades; no subscription or platform fees",
    grossMargin: "~92%",
    salesCycle: "Institutional onboarding: 4-8 weeks (KYC/AML, legal review, compliance sign-off)",
    gtmStrategy: "White-glove onboarding of institutional buyers first, then bring in sellers once liquidity is established.",
    plannedGtm: "White-glove onboarding of top-50 institutional buyers first, then sellers follow the liquidity",
    acquisitionChannels: ["Direct institutional sales", "Capital-markets conferences", "Pension-fund and endowment networks"],
    risks: ["Regulatory approval for ATS could take 12+ months", "Chicken-and-egg liquidity problem", "Incumbent relationships are deeply entrenched"],
    biggestUnknown: "Whether ATS approval from FINRA will be granted on the expected timeline or face regulatory delays",
    failureScenario: "Chicken-and-egg liquidity problem: sellers will not come without enough buyers, leading to thin order books and slow volume growth",
    idealInvestor:
      "Fintech investor with capital-markets experience who can help with broker-dealer relationships.",
    milestonesAfterRaise: ["ATS approval from FINRA", "20 institutional buyers onboarded", "$200M in quarterly trading volume"],
    capTable: { totalRaised: "$1.2M (pre-seed)", founderEquity: "75%", optionPool: "10%" },
    notableCustomers: "Three of the eight onboarded buyers are top-20 US pension funds; two insurance companies in onboarding pipeline",
    customerProof: "$42M in closed trades in first 90 days; buyers report 70% faster execution compared to traditional broker process",
    retentionEngagement: "100% buyer retention since launch; average 3.2 RFQ responses per listing within 48 hours",
  },
  {
    kind: "startup",
    id: "mock-startup-07",
    name: "Atrium Learning",
    tagline: "Teacher-in-the-loop AI tutoring that 3x's reading scores.",
    description:
      "Atrium Learning builds a reading-comprehension tutor that pairs an AI assistant with a human reading specialist. Students get one-to-one practice; teachers get auto-generated progress reports and lesson plans aligned to the science of reading.",
    sector: "Edtech",
    stage: "seed",
    location: "Brooklyn, NY",
    foundingYear: 2023,
    founder: {
      fullName: "Jordan Ellis",
      role: "CEO",
      workEmail: "jordan@atriumlearning.example",
      linkedinUrl: "https://linkedin.com/in/jordan-ellis",
      photoUrl: "/mock-assets/atrium-learning/jordan-ellis.png",
    },
    website: "https://atriumlearning.example",
    productStatus: "launched",
    founderSummary:
      "Co-founders are both former Teach For America corps members. Engineering lead came from Khan Academy. Curriculum lead has a PhD from UPenn GSE.",
    product:
      "Web app deployed in K-3 classrooms, with a teacher dashboard, a parent app, and a privacy-reviewed AI assistant.",
    keyFeatures: "AI one-on-one reading practice, auto-generated teacher progress reports, science-of-reading-aligned lesson plans",
    technicalMoat: "Proprietary reading-assessment model trained on 500K+ student sessions with teacher-validated outcome labels",
    roadmap: "Spanish-language version in Q2 2026, published RCT results in Q3, expand to 100+ schools and 15 districts by EOY",
    traction:
      "Used in 47 schools across 6 districts; reading-progress scores up an average of 1.8 grade levels in a school year.",
    mrr: "$38K",
    customers: "47 schools across 6 districts",
    growthPct: "18% MoM",
    notableSignals: "1.8 grade-level reading improvement per student per year across pilot schools",
    fundingAsk: "$3.5M seed",
    useOfFunds:
      "Hire a head of school sales, build a Spanish-language version, and run a randomized-controlled study with three districts.",
    instrument: "SAFE",
    valuationCap: "$18M",
    minCheckSize: "$100K",
    idealInvestor:
      "Edtech-focused investor who understands school-district sales cycles and has portfolio support for K-12 GTM.",
    websitePlaceholder: "atriumlearning.example",
    tags: ["edtech", "ai", "k12", "reading", "social-impact"],
    customerType: "government",
    teamMembers: [
      { name: "Jordan Ellis", role: "CEO", background: "Former Teach For America corps member. 7 years teaching K-3 in the Bronx. Backed by Y Combinator W23.", photoUrl: "/mock-assets/atrium-learning/jordan-ellis.png" },
      { name: "Maya Rodrigues", role: "CTO", background: "Engineering lead at Notion for Education. Built the structured-learning and mastery-tracking engine.", photoUrl: "/mock-assets/atrium-learning/maya-rodrigues.png" },
      { name: "Dr. Priya Anand", role: "Head of Curriculum", background: "PhD from UPenn GSE in the science of reading. Research partner at Anthropic on educational LLM alignment.", photoUrl: "/mock-assets/atrium-learning/priya-anand.png" },
    ],
    advisors: ["Former superintendent of Boston Public Schools", "VP Product at Duolingo"],
    problemStatement: "60% of US third-graders read below grade level. AI tutoring without teacher involvement has no accountability.",
    targetCustomer: "K-3 literacy coordinators and principals in Title I school districts with reading-intervention mandates",
    currentAlternatives: "Lexia Learning, Raz-Plus, and district-hired reading interventionists",
    whyAlternativesFail: "Legacy software is expensive and static; human tutors don't scale; AI-only tools lack teacher accountability",
    targetMarket: "K-3 classrooms in US school districts with Title I funding and reading-intervention mandates.",
    marketSize: "$8B US K-12 edtech market. Addressable: $1.2B in reading-intervention software.",
    marketTrend: "Post-pandemic reading scores at 30-year lows driving record district spending on literacy intervention",
    beachheadMarket: "Title I elementary schools in the US Northeast with active ESSER-funded reading-intervention mandates",
    whyNow: "Post-pandemic reading scores are at 30-year lows. Federal ESSER funding expires in 2025, creating urgency for district purchases now.",
    competitors: ["Lexia Learning (legacy, expensive)", "Raz-Plus (content library, no AI)", "Amira Learning (AI-only, no teacher loop)"],
    differentiation: "Teacher-in-the-loop model: AI handles practice, teachers get auto-generated progress reports. 3x reading-score improvement vs. AI-only.",
    whyWeWin: "Only AI reading tutor with a teacher-in-the-loop model that triples score improvement vs. AI-only competitors",
    defensibility: "Outcome data from 47 schools creates a compounding data moat — better data trains better models, which attract more schools",
    businessModel: "Per-student annual licensing to school districts.",
    revenueModel: "$45/student/year for districts, $12/month for individual families.",
    pricing: "$45/student/year for districts, $12/month for individual families",
    grossMargin: "~88%",
    salesCycle: "6-12 months for district-wide contracts; 2-4 weeks for individual school pilots",
    gtmStrategy: "Land one school in a district, prove outcomes, expand to district-wide deployment.",
    plannedGtm: "Land one school per district, publish outcome data, leverage state approved-vendor lists for expansion",
    acquisitionChannels: ["School-district procurement", "State reading-intervention approved lists", "Teacher conferences (IRA, NCTE)"],
    risks: ["ESSER funding sunset could slow procurement", "District sales cycles are 6-12 months", "AI accuracy for early readers needs constant improvement"],
    biggestUnknown: "Whether ESSER funding sunset will freeze district procurement before sustainable literacy budgets fill the gap",
    failureScenario: "Federal funding dries up, districts can't replace it with local budgets, and AI-only competitors close the outcomes gap",
    milestonesAfterRaise: ["100 schools across 15 districts", "Published RCT study", "Launch Spanish-language version"],
    capTable: { totalRaised: "$750K (friends and family)", founderEquity: "82%", optionPool: "12%" },
    notableCustomers: "Boston Public Schools, Newark Unified School District, three Brooklyn charter networks",
    customerProof: "Average 1.8 grade-level reading improvement per school year; 84% of pilot schools expanded to full deployment",
    retentionEngagement: "92% annual school renewal rate; teachers log in 4.2 times per week on average",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
  },
  {
    kind: "startup",
    id: "mock-startup-08",
    name: "Silt & Spark",
    tagline: "A neighbourhood fishmonger with same-day catch from local boats.",
    description:
      "Silt & Spark is a direct-to-consumer seafood marketplace that connects independent boats to home cooks. Customers see the boat name, the catch date, and the fishery's sustainability status; everything ships overnight in compostable packaging.",
    sector: "Consumer",
    stage: "pre_seed",
    location: "Portland, ME",
    foundingYear: 2024,
    founder: {
      fullName: "Nora Lindström",
      role: "CEO",
      workEmail: "nora@siltandspark.example",
      linkedinUrl: "https://linkedin.com/in/nora-lindstrom",
      photoUrl: "/mock-assets/silt-and-spark/nora-lindstrom.png",
    },
    website: "https://siltandspark.example",
    productStatus: "launched",
    founderSummary:
      "CEO is a former Whole Foods seafood buyer. CTO previously built marketplace infrastructure at Goldbelly. Operations lead has a master's from URI in fisheries policy.",
    product:
      "Web marketplace, weekly subscription product, compostable shipping system. Live in the Northeast.",
    keyFeatures: "Boat-to-door traceability with catch date and fishery status, overnight compostable shipping, weekly subscription curations",
    technicalMoat: "Exclusive relationships with 12 independent boats and a proprietary cold-chain logistics network optimised for same-day catch",
    roadmap: "Open second cold-pack facility in Q3 2026, expand to Mid-Atlantic markets (NY, NJ, CT) by Q4, onboard 20 new boats by next season",
    traction:
      "$240K in trailing-90-day revenue; 38% repeat-purchase rate; 12 partner boats across Maine and New Hampshire.",
    mrr: "$27K",
    customers: "850+ active home-cook subscribers",
    growthPct: "22% MoM",
    notableSignals: "38% repeat-purchase rate with word-of-mouth as the top acquisition channel",
    fundingAsk: "$1M pre-seed",
    useOfFunds:
      "Open a second cold-pack facility, build a paid-marketing engine, and onboard 20 more boats by end of next season.",
    instrument: "SAFE",
    valuationCap: "$8M",
    minCheckSize: "$50K",
    idealInvestor:
      "Consumer-marketplace investor comfortable with cold-chain economics. Bonus if they know food-and-beverage CPG channels.",
    websitePlaceholder: "siltandspark.example",
    tags: ["consumer", "marketplace", "food", "sustainability", "dtc"],
    customerType: "consumer",
    teamMembers: [
      { name: "Nora Lindström", role: "CEO", background: "Former Whole Foods seafood buyer. 10 years in sustainable food sourcing. Advisor at Airtable for food-supply workflows.", photoUrl: "/mock-assets/silt-and-spark/nora-lindstrom.png" },
      { name: "Raj Iyer", role: "CTO", background: "Built marketplace infrastructure at Airtable. Previously scaled a food-commerce platform to $200M GMV.", photoUrl: "/mock-assets/silt-and-spark/raj-iyer.png" },
      { name: "Ben Calloway", role: "Head of Operations", background: "Master's in fisheries policy from URI. Former NOAA consultant. Operations at a Sequoia-backed food startup.", photoUrl: "/mock-assets/silt-and-spark/ben-calloway.png" },
    ],
    advisors: ["Former CEO of a regional seafood distributor", "VP Supply Chain at HelloFresh"],
    problemStatement: "Consumers want fresh, sustainable seafood but have no way to know where their fish came from or when it was caught.",
    targetCustomer: "Health-conscious home cooks in the US Northeast spending $100+/month on groceries who care about food provenance",
    currentAlternatives: "Wild Alaskan Company subscription boxes, local fish markets, and supermarket seafood counters",
    whyAlternativesFail: "Subscription boxes offer no boat-level traceability; local fish markets have no online presence; supermarket seafood is days old with opaque sourcing",
    targetMarket: "Health-conscious home cooks in the US Northeast who spend $100+/month on groceries.",
    marketSize: "$17B US seafood market. Addressable: $2B in DTC and specialty-retail seafood.",
    marketTrend: "Consumer demand for food traceability at all-time highs; sustainable-seafood market growing 12% YoY",
    beachheadMarket: "Affluent coastal communities in Maine and New Hampshire with high organic-grocery spend",
    whyNow: "Consumer demand for traceability is at an all-time high. Compostable cold-pack shipping is finally cost-effective.",
    competitors: ["Fulton Fish Market (wholesale, not DTC)", "Wild Alaskan Company (subscription box, limited boats)", "Local fish markets (no online presence)"],
    differentiation: "Boat-to-door traceability: customers see the boat name, catch date, and fishery sustainability status.",
    whyWeWin: "Only DTC seafood marketplace that shows the exact boat, catch date, and sustainability status for every order",
    defensibility: "Direct boat partnerships and a purpose-built cold-chain network that would take a competitor 18+ months to replicate",
    businessModel: "Marketplace take rate (18-22%) on orders plus weekly subscription product.",
    revenueModel: "Average order value $65, 18% take rate. Subscription $49/week.",
    pricing: "Average order $65 à la carte, $49/week subscription box",
    grossMargin: "~35% (cold-chain logistics are expensive)",
    salesCycle: "Instant consumer purchase; 2-4 weeks to onboard a new boat partner",
    gtmStrategy: "Start hyperlocal (Maine coast), prove unit economics, expand down the Eastern Seaboard.",
    plannedGtm: "Hyperlocal expansion down the Eastern Seaboard; influencer partnerships with sustainable-food creators",
    acquisitionChannels: ["Instagram and food blogs", "Farmers market pop-ups", "Partnership with sustainable-food influencers"],
    risks: ["Cold-chain logistics complexity and cost", "Seasonal catch variability", "Scaling beyond Northeast requires new boat relationships"],
    biggestUnknown: "Whether unit economics hold as we expand beyond Maine, where cold-chain distances are short",
    failureScenario: "Cold-chain costs spike as we expand geographically, eroding margins; seasonal catch variability frustrates subscribers",
    milestonesAfterRaise: ["$1M trailing-90-day revenue", "Second cold-pack facility", "Expand to Mid-Atlantic (NY, NJ, CT)"],
    capTable: { totalRaised: "$180K (angel pre-seed)", founderEquity: "88%", optionPool: "10%" },
    notableCustomers: "800+ repeat subscribers in Portland and Boston metro areas; two Michelin-starred restaurants in trial",
    customerProof: "38% repeat-purchase rate; NPS of 72 among subscribers; average subscriber stays 6.5 months",
    retentionEngagement: "38% monthly repeat-purchase rate; 72 NPS; 65% of subscribers order weekly",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
  },
  {
    kind: "startup",
    id: "mock-startup-09",
    name: "Beacon Trace",
    tagline: "Software supply-chain attestations for regulated industries.",
    description:
      "Beacon Trace generates and verifies cryptographic attestations of every software artefact that ships into a regulated environment. We help defence, finance, and healthcare buyers comply with the new SBOM and Executive Order 14028 requirements without slowing down their vendors.",
    sector: "B2B SaaS",
    stage: "seed",
    location: "Washington, DC",
    foundingYear: 2023,
    founder: {
      fullName: "Alex Mercer",
      role: "CEO",
      workEmail: "alex@beacontrace.example",
      linkedinUrl: "https://linkedin.com/in/alex-mercer",
      photoUrl: "/mock-assets/beacon-trace/alex-mercer.png",
    },
    website: "https://beacontrace.example",
    productStatus: "revenue_generating",
    founderSummary:
      "Founder team is former NSA Tailored Access plus a security-tools veteran from Snyk. Advisors include the former CISO of a top-3 US bank.",
    product:
      "SaaS attestation service plus open-source Sigstore-compatible client. Used by two defence primes.",
    keyFeatures: "Cryptographic attestation generation, Sigstore-compatible verification, automated SBOM compliance reporting",
    technicalMoat: "Purpose-built attestation engine with FedRAMP Moderate authorization in progress — a 12-18 month moat for competitors",
    roadmap: "Complete FedRAMP Moderate in Q2 2026, expand to European DORA compliance in Q4, reach 15 Fortune 500 customers by EOY",
    traction:
      "$420K ARR, three Fortune 500 customers, FedRAMP Moderate authorization in progress.",
    mrr: "$35K",
    customers: "8 enterprise customers including 3 Fortune 500",
    growthPct: "12% MoM",
    notableSignals: "Two defence prime contractors in production; FedRAMP Moderate authorization in progress",
    fundingAsk: "$6M seed",
    useOfFunds:
      "Hire two security engineers, finish FedRAMP, expand into the European DORA-compliance market.",
    instrument: "Priced equity",
    valuationCap: "$30M pre-money",
    minCheckSize: "$250K",
    idealInvestor:
      "B2B SaaS lead with a security or regulated-software portfolio. Comfortable with long enterprise sales cycles.",
    websitePlaceholder: "beacontrace.example",
    tags: ["b2b-saas", "security", "compliance", "supply-chain", "fedramp", "regulated"],
    customerType: "enterprise",
    teamMembers: [
      { name: "Alex Mercer", role: "CEO", background: "Former NSA Tailored Access Operations. 15 years in offensive security. Advisor to GitHub Advanced Security.", photoUrl: "/mock-assets/beacon-trace/alex-mercer.png" },
      { name: "Jess Lin", role: "CTO", background: "Security-tools veteran from GitHub Advanced Security. Built the container-scanning and secret-detection pipeline.", photoUrl: "/mock-assets/beacon-trace/jess-lin.png" },
      { name: "David O'Brien", role: "VP Sales", background: "Enterprise sales lead at Slack. $40M quota attainment across Fortune 500 security teams.", photoUrl: "/mock-assets/beacon-trace/david-obrien.png" },
    ],
    advisors: ["Former CISO of a top-3 US bank", "Ex-NIST supply-chain security lead"],
    problemStatement: "Regulated buyers (defence, finance, healthcare) need cryptographic proof of every software artefact's provenance, but today's tools are manual and fragmented.",
    targetCustomer: "CISOs and compliance officers at Fortune 500 companies with Executive Order 14028 obligations",
    currentAlternatives: "Chainguard for container hardening, Anchore for SBOM generation, manual spreadsheet-based attestation tracking",
    whyAlternativesFail: "Existing tools handle pieces of the problem but none provide end-to-end generate-sign-verify in a FedRAMP-ready platform",
    targetMarket: "Fortune 500 companies in defence, finance, and healthcare with Executive Order 14028 compliance obligations.",
    marketSize: "$5.4B software supply-chain security market. Addressable: $1.8B in attestation and SBOM tooling.",
    marketTrend: "Executive Order 14028 and CISA directives making software supply-chain attestation mandatory for federal vendors",
    beachheadMarket: "US defence primes and federal software vendors subject to Executive Order 14028 SBOM mandates",
    whyNow: "Executive Order 14028 and new CISA directives mandate SBOM and attestation for federal software vendors by 2025.",
    competitors: ["Chainguard (container hardening)", "Anchore (SBOM generation)", "Snyk (vulnerability scanning, not attestation)"],
    differentiation: "End-to-end attestation: generate, sign, and verify in one platform. Sigstore-compatible, FedRAMP-ready.",
    whyWeWin: "Only platform that generates, signs, and verifies attestations end-to-end with FedRAMP-ready infrastructure",
    defensibility: "FedRAMP authorization is a 12-18 month process that creates a durable barrier; early government contracts build switching-cost moat",
    businessModel: "Annual SaaS contracts with enterprise customers. Tiered by number of artefacts attested.",
    revenueModel: "Starting at $120K/year for mid-market, $500K+ for Fortune 500.",
    pricing: "$120K/year for mid-market, $500K+ for Fortune 500 with custom SLAs",
    grossMargin: "~87%",
    salesCycle: "9-18 months for Fortune 500; 3-6 months for mid-market with existing compliance mandates",
    gtmStrategy: "Top-down enterprise sales to CISO and compliance teams. FedRAMP as a wedge for federal contracts.",
    plannedGtm: "Top-down enterprise sales via CISO advisory board referrals; FedRAMP as wedge for federal contract expansion",
    acquisitionChannels: ["CISO advisory board referrals", "Federal procurement channels", "RSA and Black Hat conferences"],
    risks: ["FedRAMP authorization timeline could slip", "Large competitors (Snyk, Palo Alto) could add attestation", "Long enterprise sales cycles (9-18 months)"],
    biggestUnknown: "Whether FedRAMP Moderate authorization timeline will hold or slip another quarter",
    failureScenario: "Large incumbents (Snyk, Palo Alto Networks) add native attestation features, commoditising the standalone market",
    milestonesAfterRaise: ["FedRAMP Moderate authorization", "10 Fortune 500 customers", "Expand to European DORA compliance"],
    capTable: { totalRaised: "$1.2M (pre-seed)", founderEquity: "78%", optionPool: "10%" },
    notableCustomers: "Two top-10 US defence prime contractors, a Fortune 100 financial-services firm, a major healthcare system",
    customerProof: "$420K ARR with 100% logo retention; one defence prime expanded from pilot to enterprise-wide in 4 months",
    retentionEngagement: "100% annual logo retention; average customer attests 15K+ artefacts per month",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
  },
  {
    kind: "startup",
    id: "mock-startup-10",
    name: "Northbeam Robotics",
    tagline: "Autonomous mobile robots for mid-market warehouses.",
    description:
      "Northbeam Robotics ships a turnkey autonomous-mobile-robot fleet for warehouses too small for a Symbotic deployment. Our robots install in a weekend, integrate with existing WMS systems, and pay back capex inside 14 months at typical labour costs.",
    sector: "Hardware",
    stage: "series_a",
    location: "Pittsburgh, PA",
    foundingYear: 2022,
    founder: {
      fullName: "Dr. Claire Yeung",
      role: "CEO",
      workEmail: "claire@northbeamrobotics.example",
      linkedinUrl: "https://linkedin.com/in/claire-yeung",
      photoUrl: "/mock-assets/northbeam-robotics/claire-yeung.png",
    },
    website: "https://northbeamrobotics.example",
    productStatus: "revenue_generating",
    founderSummary:
      "Founding team came out of CMU's RI plus operations leadership from a previous warehouse-automation exit.",
    product:
      "AMR fleet plus orchestration software. Installed in seven facilities across the Midwest.",
    keyFeatures: "Weekend-install AMR fleet, plug-and-play WMS integration, real-time fleet orchestration software",
    technicalMoat: "Proprietary obstacle-avoidance stack with 6 patents optimised for cluttered mid-market warehouse environments",
    roadmap: "Scale to 20 facilities by Q3 2026, launch ambient-temperature 3PL product line in Q1 2027, build 50-person field-engineering team",
    traction:
      "$3.4M in trailing-12-month revenue, four signed enterprise contracts, one expansion to a second site.",
    mrr: "$283K",
    customers: "7 warehouse facilities with 4 signed enterprise contracts",
    growthPct: "14% MoM",
    notableSignals: "One customer expanded to a second site after 6-month ROI validation; 14-month capex payback confirmed",
    fundingAsk: "$22M Series A",
    useOfFunds:
      "Scale manufacturing, build out a 50-person field-engineering team, expand into ambient-temperature 3PL.",
    instrument: "Priced equity",
    valuationCap: "$90M pre-money",
    minCheckSize: "$1M",
    idealInvestor:
      "Series A lead who has scaled robotics or warehouse-automation businesses before. Comfortable with hardware capex.",
    websitePlaceholder: "northbeamrobotics.example",
    tags: ["hardware", "robotics", "warehouses", "logistics", "automation", "deeptech"],
    customerType: "enterprise",
    teamMembers: [
      { name: "Dr. Claire Yeung", role: "CEO", background: "CMU Robotics Institute PhD. Led autonomous-navigation research. Previously at Replit on embedded systems education.", photoUrl: "/mock-assets/northbeam-robotics/claire-yeung.png" },
      { name: "Tom Bassett", role: "COO", background: "VP Operations at a Sequoia-backed warehouse-automation company. Scaled 3PL operations to 8 sites.", photoUrl: "/mock-assets/northbeam-robotics/tom-bassett.png" },
      { name: "Ankit Desai", role: "VP Engineering", background: "Perception lead at OpenAI Robotics research. 6 patents in obstacle avoidance and spatial reasoning.", photoUrl: "/mock-assets/northbeam-robotics/ankit-desai.png" },
    ],
    advisors: ["Former CTO of Kiva Systems (pre-Amazon acquisition)", "VP Logistics at a top-5 3PL"],
    problemStatement: "Mid-market warehouses (10K-100K sq ft) can't afford Symbotic or Locus-scale automation but face 30%+ labour turnover.",
    targetCustomer: "Operations VPs at mid-market warehouse operators (10K-100K sq ft) with 30%+ annual labour turnover",
    currentAlternatives: "Locus Robotics, 6 River Systems (Shopify-owned), and manual labour with conveyor belts",
    whyAlternativesFail: "Enterprise AMR solutions require 6-month integrations and $1M+ deployments; manual labour faces 30%+ turnover and rising costs",
    targetMarket: "Mid-market warehouse operators in the US Midwest and Southeast with 10K-100K sq ft facilities.",
    marketSize: "$9B warehouse automation market. Addressable: $2.5B in mid-market AMR solutions.",
    marketTrend: "Warehouse labour costs up 22% since 2020; LiDAR sensor costs down 80%; mid-market automation remains massively underserved",
    beachheadMarket: "Mid-market 3PL and e-commerce fulfilment warehouses in the US Midwest with high labour turnover",
    whyNow: "Labour costs have risen 22% since 2020. LiDAR costs dropped 80%. Weekend-install capability eliminates integration risk.",
    competitors: ["Locus Robotics (enterprise-focused)", "6 River Systems (Shopify-owned)", "Fetch Robotics (Zebra-owned)"],
    differentiation: "Turnkey fleet that installs in a weekend, integrates with any WMS, and pays back capex in 14 months.",
    whyWeWin: "Only turnkey AMR fleet that installs in a weekend, integrates with any WMS, and pays back capex in 14 months",
    defensibility: "6 patents in obstacle avoidance, proprietary orchestration software, and deep field-deployment expertise that takes years to replicate",
    businessModel: "Hardware lease-to-own plus RaaS (Robots-as-a-Service) monthly subscription.",
    revenueModel: "Lease: $3K/robot/month. Purchase: $45K/robot + $500/month software.",
    pricing: "Lease: $3K/robot/month. Purchase: $45K/robot + $500/month software subscription",
    grossMargin: "~40% on hardware, ~80% on software/service",
    salesCycle: "3-6 months from demo to deployment; expansion deals close in 4-8 weeks",
    gtmStrategy: "Direct sales to warehouse operators. Land with 5-10 robots, expand as they see ROI.",
    plannedGtm: "Direct sales to warehouse operators; land with 5-10 robots, prove ROI, expand fleet across sites",
    acquisitionChannels: ["Warehouse trade shows (ProMat, MODEX)", "3PL partnerships", "WMS vendor integrations"],
    risks: ["Manufacturing scale-up with a single contract manufacturer", "Competition from well-funded incumbents", "Customer capex hesitancy in a recession"],
    biggestUnknown: "Whether contract manufacturing can scale fast enough to meet demand without quality degradation",
    failureScenario: "Well-funded incumbents (Locus, Zebra-owned Fetch) move downmarket with competitive mid-market pricing",
    milestonesAfterRaise: ["20 facilities deployed", "50-person field-engineering team", "Launch ambient-temperature 3PL product line"],
    capTable: { totalRaised: "$4.5M (seed)", founderEquity: "68%", optionPool: "12%" },
    notableCustomers: "Three regional 3PL operators in Ohio and Michigan, a national e-commerce fulfilment provider",
    customerProof: "14-month capex payback validated at 4 sites; one customer expanded from 8 to 22 robots within 6 months",
    retentionEngagement: "100% customer retention; average fleet uptime of 97.3%; all customers renewed or expanded",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
  },
  {
    kind: "startup",
    id: "mock-startup-11",
    name: "Tessera Bio",
    tagline: "Bench-to-clinic protein-design platform powered by retrieval-augmented LLMs.",
    description:
      "Tessera Bio uses retrieval-augmented protein-language models to design therapeutic candidates 10x faster than conventional discovery. Today we partner with two pharma companies on rare-disease enzyme replacement therapies and target programmes.",
    sector: "Biotech",
    stage: "series_a",
    location: "Cambridge, MA",
    foundingYear: 2022,
    founder: {
      fullName: "Dr. Hannah Reis",
      role: "CEO",
      workEmail: "hannah@tesserabio.example",
      linkedinUrl: "https://linkedin.com/in/hannah-reis",
      photoUrl: "/mock-assets/tessera-bio/hannah-reis.png",
    },
    website: "https://tesserabio.example",
    productStatus: "revenue_generating",
    founderSummary:
      "CEO came from Genentech computational biology. Co-founder is a Broad Institute principal investigator. Six PhDs on staff.",
    product:
      "Internal protein-design platform powering partnered programmes. Two candidates in IND-enabling studies.",
    keyFeatures: "Retrieval-augmented protein-language models, bench-to-IND integrated pipeline, in-house wet-lab validation",
    technicalMoat: "Proprietary retrieval-augmented architecture grounds designs in real clinical data; 6 PhDs and 40+ publications on the team",
    roadmap: "First IND filing in Q3 2026, third pharma partnership in Q4, launch internal pipeline programme in CNS rare disease by Q1 2027",
    traction:
      "$11M in signed partnership revenue across two pharma deals. One programme cleared lead-optimization milestones a quarter early.",
    mrr: "N/A (milestone-based partnership revenue)",
    customers: "2 top-20 pharma partners with signed deals",
    growthPct: "N/A (lumpy milestone-based revenue)",
    notableSignals: "One programme cleared lead-optimization milestones a quarter ahead of schedule",
    fundingAsk: "$35M Series A",
    useOfFunds:
      "Stand up internal pipeline programmes, expand wet-lab capacity in Cambridge, hire two senior medicinal chemists.",
    instrument: "Priced equity",
    valuationCap: "$140M pre-money",
    minCheckSize: "$2M",
    idealInvestor:
      "Biotech-native lead with experience in platform-plus-pipeline economics and regulatory strategy.",
    websitePlaceholder: "tesserabio.example",
    tags: ["biotech", "ai", "deeptech", "therapeutics", "platform", "regulated"],
    customerType: "enterprise",
    teamMembers: [
      { name: "Dr. Hannah Reis", role: "CEO", background: "Computational biology at Genentech for 8 years. Led two IND filings. Science advisor at Anthropic on bio-AI safety.", photoUrl: "/mock-assets/tessera-bio/hannah-reis.png" },
      { name: "Dr. Sanjay Mukherjee", role: "CSO", background: "Broad Institute principal investigator. 40+ publications in protein engineering. Research collaboration with OpenAI on structure prediction.", photoUrl: "/mock-assets/tessera-bio/sanjay-mukherjee.png" },
      { name: "Elena Vasquez", role: "VP Partnerships", background: "Business development at Stripe for Life Sciences. Closed $50M+ in platform deals with pharma companies.", photoUrl: "/mock-assets/tessera-bio/elena-vasquez.png" },
    ],
    advisors: ["Former CMO of Vertex Pharmaceuticals", "Partner at ARCH Venture Partners"],
    problemStatement: "Traditional protein design takes 3-5 years per candidate. Rare-disease patients can't wait that long.",
    targetCustomer: "VP-level R&D and business-development leads at top-20 pharma companies with rare-disease pipeline gaps",
    currentAlternatives: "Absci (generative antibodies), Generate Biomedicines (protein design), traditional CRO-based discovery",
    whyAlternativesFail: "Generative-only approaches lack grounding in clinical data; traditional discovery takes 3-5 years per candidate",
    targetMarket: "Top-20 pharma companies seeking AI-powered protein-design partnerships for rare-disease enzyme replacement.",
    marketSize: "$67B biologics market. Addressable: $8B in AI-driven protein design and discovery.",
    marketTrend: "Protein-language models reaching therapeutic-grade accuracy; rare-disease regulatory incentives (orphan drug designation) accelerating",
    beachheadMarket: "Rare-disease enzyme-replacement therapies where speed-to-IND is the critical competitive factor",
    whyNow: "Retrieval-augmented protein-language models have reached the accuracy threshold for therapeutic-grade design.",
    competitors: ["Absci (generative antibodies)", "Generate Biomedicines (protein design)", "Evozyne (enzyme engineering)"],
    differentiation: "Retrieval-augmented approach grounds designs in real clinical data. Two candidates already in IND-enabling studies.",
    whyWeWin: "Retrieval-augmented approach produces candidates grounded in clinical reality — two already in IND-enabling studies",
    defensibility: "Proprietary training data from pharma partnerships, 40+ publications, and two IND-enabling candidates that validate the platform",
    businessModel: "Pharma partnerships with upfront fees, milestone payments, and downstream royalties. Internal pipeline for owned programmes.",
    revenueModel: "Partnership deals: $3-8M upfront + milestones. Internal programmes: potential blockbuster royalties.",
    pricing: "$3-8M upfront per partnership plus milestone payments and downstream royalties",
    grossMargin: "~70% on partnership revenue (wet-lab costs are the main COGS)",
    salesCycle: "6-12 months for initial pharma partnership; expansion deals close in 3-6 months",
    gtmStrategy: "Target rare-disease programmes at top-20 pharma where speed is critical and traditional methods have failed.",
    plannedGtm: "Target rare-disease BD teams at top-20 pharma; publish platform validation results to build inbound pipeline",
    acquisitionChannels: ["Pharma BD relationships", "Scientific conferences (AACR, ASHG)", "Published research and preprints"],
    risks: ["Clinical failure of lead candidates", "Platform-vs-pipeline resource allocation tension", "Dependence on two large pharma partners"],
    biggestUnknown: "Whether lead candidates will clear IND-enabling toxicology studies without requiring significant redesign",
    failureScenario: "Clinical failure of both lead candidates shakes pharma partner confidence; platform credibility takes 2+ years to rebuild",
    milestonesAfterRaise: ["First IND filing", "Third pharma partnership", "Launch internal pipeline programme in a new disease area"],
    capTable: { totalRaised: "$8M (seed and bridge)", founderEquity: "62%", optionPool: "10%" },
    notableCustomers: "Two top-20 pharma companies (under NDA) with rare-disease enzyme-replacement programmes",
    customerProof: "$11M in signed partnership revenue; one programme hit lead-optimization milestones a quarter early",
    retentionEngagement: "Both pharma partners expanded scope after initial results; 100% partner retention",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
  },
  {
    kind: "startup",
    id: "mock-startup-12",
    name: "Drift Markets",
    tagline: "Onchain liquidity for the long tail of regional currencies.",
    description:
      "Drift Markets builds onchain market-making infrastructure for the 80+ regional currencies that today have nearly zero electronic FX liquidity. Our partners use Drift to settle cross-border B2B payments in seconds at fees 10x cheaper than correspondent-bank rails.",
    sector: "Web3",
    stage: "seed",
    location: "Singapore",
    foundingYear: 2023,
    founder: {
      fullName: "Leo Tan",
      role: "CEO",
      workEmail: "leo@driftmarkets.example",
      linkedinUrl: "https://linkedin.com/in/leo-tan",
      photoUrl: "/mock-assets/drift-markets/leo-tan.png",
    },
    website: "https://driftmarkets.example",
    productStatus: "launched",
    founderSummary:
      "CEO ran FX strategy at a top-tier crypto market maker. CTO previously built oracle infrastructure at a major DeFi protocol. Both holders of CFA and Series 7.",
    product:
      "Permissioned market-making engine plus a settlement API. Live across 11 currency pairs.",
    keyFeatures: "Onchain market-making engine, instant settlement API for PSPs, permissioned liquidity pools for regulated partners",
    technicalMoat: "Proprietary market-making algorithms optimised for thin frontier-currency order books; MAS regulatory licence in Singapore",
    roadmap: "Add 20 currency pairs by Q3 2026, obtain PSP licences in 3 new jurisdictions by Q4, reach $500M monthly notional volume",
    traction:
      "$80M in trailing-30-day notional volume, $230K in trailing-90-day revenue, two regulated PSP partners.",
    mrr: "$77K",
    customers: "2 regulated PSP partners with 15+ B2B payment platforms in pipeline",
    growthPct: "20% MoM",
    notableSignals: "$80M trailing-30-day notional volume across 11 currency pairs with two regulated PSP partners",
    fundingAsk: "$5M seed",
    useOfFunds:
      "Add 20 currency pairs, hire compliance and licensing leads, build into the Asia-Pacific PSP ecosystem.",
    instrument: "SAFE",
    valuationCap: "$25M",
    minCheckSize: "$200K",
    idealInvestor:
      "Web3-fluent investor who understands FX and cross-border payments and is comfortable with regulated rails.",
    websitePlaceholder: "driftmarkets.example",
    tags: ["web3", "fintech", "fx", "payments", "defi", "regulated"],
    customerType: "enterprise",
    teamMembers: [
      { name: "Leo Tan", role: "CEO", background: "FX strategy lead at Stripe Treasury. CFA and Series 7 holder. Previously at Sequoia as a fintech scout.", photoUrl: "/mock-assets/drift-markets/leo-tan.png" },
      { name: "Anya Petrov", role: "CTO", background: "Infrastructure engineer at Supabase, built real-time price feeds for 50+ currency pairs across DeFi protocols.", photoUrl: "/mock-assets/drift-markets/anya-petrov.png" },
      { name: "Omar Fayed", role: "Head of Compliance", background: "Former MAS (Monetary Authority of Singapore) licensing officer. Advisor to Stripe on cross-border compliance.", photoUrl: "/mock-assets/drift-markets/omar-fayed.png" },
    ],
    advisors: ["Former head of FX at a top-3 crypto exchange", "Partner at a Singapore payments-regulation law firm"],
    problemStatement: "80+ regional currencies have near-zero electronic FX liquidity, making B2B cross-border payments slow, expensive, and opaque.",
    targetCustomer: "Payment service providers and B2B payment platforms serving emerging-market currency corridors",
    currentAlternatives: "Correspondent banking networks, Wise (limited frontier coverage), Airwallex (enterprise, limited regional currencies)",
    whyAlternativesFail: "Banks are slow and expensive for frontier currencies; fintech competitors don't support the long tail of 80+ regional pairs",
    targetMarket: "Payment service providers (PSPs) and B2B payment platforms serving emerging-market corridors.",
    marketSize: "$7.5T global FX market. Addressable: $150B in underserved regional currency pairs.",
    marketTrend: "Stablecoin infrastructure maturing for regulated settlement; correspondent-bank rails shrinking as compliance costs rise",
    beachheadMarket: "Southeast Asian PSPs serving intra-ASEAN B2B payment corridors with thin FX liquidity",
    whyNow: "Stablecoin infrastructure is mature enough for regulated settlement. PSPs need new liquidity sources as correspondent-bank rails shrink.",
    competitors: ["Wise (consumer FX, limited regional coverage)", "Airwallex (enterprise, limited frontier currencies)", "Traditional correspondent banks"],
    differentiation: "Onchain market-making engine that provides instant liquidity for frontier currencies at 10x lower fees than bank rails.",
    whyWeWin: "Only onchain market-making engine providing instant liquidity for frontier currencies at 10x lower fees than bank rails",
    defensibility: "Regulatory licences, proprietary market-making algorithms, and PSP partnerships that take 6-12 months to replicate",
    businessModel: "Spread-based revenue on FX transactions plus API licensing fees for PSP partners.",
    revenueModel: "5-15bps spread per trade. API licensing: $25K/month per PSP partner.",
    pricing: "5-15bps spread per trade; API licensing at $25K/month per PSP partner",
    grossMargin: "~82%",
    salesCycle: "3-6 months for PSP partnerships; 1-2 months for API integration after contract",
    gtmStrategy: "Partner with 2-3 large PSPs as liquidity providers, then expand currency-pair coverage.",
    plannedGtm: "Partner with 2-3 anchor PSPs as liquidity providers, then expand currency-pair coverage to attract more PSPs",
    acquisitionChannels: ["PSP partnerships", "Payments conferences (Money20/20, Singapore Fintech Festival)", "Regulator introductions"],
    risks: ["Regulatory fragmentation across jurisdictions", "Counterparty risk in frontier markets", "Stablecoin regulatory uncertainty"],
    biggestUnknown: "Whether regulatory fragmentation across ASEAN jurisdictions will slow multi-market expansion",
    failureScenario: "Stablecoin regulatory crackdown in key jurisdictions cuts off settlement rails; PSP partners pull back",
    milestonesAfterRaise: ["30 currency pairs live", "PSP licenses in 3 new jurisdictions", "$500M monthly notional volume"],
    capTable: { totalRaised: "$1.5M (pre-seed)", founderEquity: "75%", optionPool: "10%" },
    notableCustomers: "Two MAS-regulated PSPs processing $80M+ monthly in cross-border B2B payments",
    customerProof: "$80M trailing-30-day notional volume; 11 currency pairs live; both PSP partners renewed after pilot",
    retentionEngagement: "100% PSP partner retention; average daily volume per pair growing 15% month-over-month",
    pitchDeckUrl: null,
    videoUrl: null,
    photos: [],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
//  Investors (12) — what founders see during onboarding
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_INVESTORS: InvestorRecommendation[] = [
  {
    kind: "investor",
    id: "mock-investor-01",
    name: "Northstone Ventures",
    tagline: "Series A devtools and enterprise infrastructure.",
    investorType: "firm",
    checkRange: "$3M – $8M",
    stages: ["series_a"],
    sectors: ["Developer tools", "B2B SaaS", "Infrastructure"],
    geography: "US + Canada",
    equityPreference: "Lead-only, 15-22% target ownership",
    thesis:
      "We back technical founders who are rebuilding the developer-experience and enterprise-infrastructure layers from first principles, with a clear path to a $100M ARR business.",
    portfolio: [
      "Switchboard (devtools, Series B)",
      "Liminal Cloud (infra, acquired by Snowflake)",
      "Argus Logs (observability, Series A)",
      "Ribbon (devtools, seed)",
      "Casing (security, Series A)",
    ],
    helpsWith: [
      "Series B narrative and metrics work",
      "Enterprise GTM hires (VP Sales, head of CS)",
      "Pricing and packaging for technical buyers",
      "Board governance on engineering-led teams",
    ],
    founderQualities: [
      "Has shipped to engineers at scale before",
      "Comfortable being the first sales rep",
      "Strong opinions on developer experience",
    ],
    websitePlaceholder: "northstoneventures.example",
    tags: ["devtools", "b2b-saas", "infrastructure", "series-a", "lead"],
  },
  {
    kind: "investor",
    id: "mock-investor-02",
    name: "Halverson Capital",
    tagline: "Healthcare and life-sciences investing with a 25-year operator network.",
    investorType: "firm",
    checkRange: "$5M – $20M",
    stages: ["series_a", "series_b_plus"],
    sectors: ["Healthcare", "Biotech", "Health IT"],
    geography: "US + UK",
    equityPreference: "Lead, board seat, 18-25% target ownership",
    thesis:
      "We invest in companies that change cost-of-care or clinical outcomes for at least one diagnosis category. We bring deep payer, provider, and regulatory networks.",
    portfolio: [
      "Marrow Health (registry, seed-led)",
      "Helix Pediatrics (clinical SaaS, Series B)",
      "Caracal Therapeutics (biotech, IPO)",
      "Lumen Health (HRT, Series A)",
      "Brae Diagnostics (lab software, acquired)",
    ],
    helpsWith: [
      "FDA strategy and regulatory affairs hires",
      "Hospital-network introductions",
      "Payer-contract negotiations",
      "Clinical advisory board recruiting",
    ],
    founderQualities: [
      "Clinical or scientific co-founder on the team",
      "Patient-impact thesis they can articulate in plain English",
      "Realistic about regulatory timelines",
    ],
    websitePlaceholder: "halversoncapital.example",
    tags: ["healthcare", "biotech", "regulated", "series-a", "series-b", "lead"],
  },
  {
    kind: "investor",
    id: "mock-investor-03",
    name: "Lila Patel",
    tagline: "Solo angel and former Stripe operator. Fintech and B2B SaaS.",
    investorType: "angel",
    checkRange: "$50K – $250K",
    stages: ["pre_seed", "seed"],
    sectors: ["Fintech", "B2B SaaS"],
    geography: "Global, English-speaking",
    equityPreference: "Follow-on or co-invest only",
    thesis:
      "I write small first checks for fintech and B2B SaaS founders who are building for a specific buyer persona I've worked with before — controllers, AP teams, and platform-risk leads.",
    portfolio: [
      "Quill & Ledger (fintech, pre-seed)",
      "Padlock Risk (security, seed)",
      "Tabletop Payments (fintech, seed)",
      "Beam Reporting (B2B SaaS, pre-seed)",
      "Hatchpoint (HR tech, seed)",
    ],
    helpsWith: [
      "Operator intros at Stripe, Brex, and Mercury",
      "Pricing pages and self-serve onboarding teardowns",
      "Recruiting first 5-10 engineering and design hires",
    ],
    founderQualities: [
      "Has owned at least one B2B SaaS roadmap end-to-end before",
      "Writes well — clear thinking on the product page",
      "Customer-obsessed in conversation",
    ],
    websitePlaceholder: "lila.example",
    tags: ["fintech", "b2b-saas", "angel", "pre-seed", "seed", "operator"],
  },
  {
    kind: "investor",
    id: "mock-investor-04",
    name: "Pylon Climate Capital",
    tagline: "Series A climate-hardware and industrial decarbonisation.",
    investorType: "firm",
    checkRange: "$10M – $25M",
    stages: ["series_a"],
    sectors: ["Climate", "Hardware", "Industrial"],
    geography: "North America + Europe",
    equityPreference: "Lead, 18-22% target ownership",
    thesis:
      "We lead climate-hardware Series A rounds when a company has at least one paying industrial customer and a credible IRA-aligned path to gigawatt-scale capacity.",
    portfolio: [
      "Polestar Climate (heat pumps, Series A)",
      "Foundry Hydrogen (electrolysers, Series A)",
      "Mantle Energy (storage, Series B)",
      "Cadence Recycling (chemical recycling, Series A)",
      "Auger Cement (cement, seed-extension)",
    ],
    helpsWith: [
      "IRA tax-credit and DOE-loan navigation",
      "Industrial customer introductions",
      "Manufacturing-engineering hires",
      "Long-form Series-B narrative work",
    ],
    founderQualities: [
      "Hardware shipping experience at scale",
      "Comfort with industrial-customer sales cycles",
      "Realistic about capex and unit economics",
    ],
    websitePlaceholder: "pylonclimate.example",
    tags: ["climate", "hardware", "industrial", "deeptech", "series-a", "lead", "ira"],
  },
  {
    kind: "investor",
    id: "mock-investor-05",
    name: "Ravi Shah",
    tagline: "Devtools angel. First-cheque writer for technical founders.",
    investorType: "angel",
    checkRange: "$25K – $150K",
    stages: ["pre_seed", "seed"],
    sectors: ["Developer tools", "Infrastructure", "AI"],
    geography: "Global",
    equityPreference: "Follow",
    thesis:
      "I write small first checks for technical founders building developer-experience and infrastructure tools. I prefer founders shipping in public.",
    portfolio: [
      "Lattice Forge (devtools, seed)",
      "Stamp Sigchain (security, seed)",
      "Modular Bench (AI infra, seed)",
      "Codepath Labs (devtools, pre-seed)",
      "Glimmer Logs (observability, pre-seed)",
    ],
    helpsWith: [
      "Recruiting senior engineers from FAANG",
      "Open-source distribution strategy",
      "Founders-as-DevRel playbook",
    ],
    founderQualities: [
      "Ships in public — public PRs, blog posts, conference talks",
      "Prior devtools or platform experience",
      "Clear writer with strong opinions",
    ],
    websitePlaceholder: "ravi.example",
    tags: ["devtools", "ai", "infrastructure", "angel", "pre-seed", "operator"],
  },
  {
    kind: "investor",
    id: "mock-investor-06",
    name: "Beacon Public Ventures",
    tagline: "Govtech, edtech, and impact-oriented B2B SaaS.",
    investorType: "firm",
    checkRange: "$1M – $5M",
    stages: ["seed", "series_a"],
    sectors: ["Edtech", "Govtech", "Civic Tech"],
    geography: "US",
    equityPreference: "Lead or co-lead, 12-18% target ownership",
    thesis:
      "We back companies whose customer is a school district, a city government, or a nonprofit health system. We help with procurement and grant-funded GTM.",
    portfolio: [
      "Atrium Learning (edtech, seed)",
      "Civic Stack (govtech, Series A)",
      "Resolve Care (community-health SaaS, seed)",
      "Foundation Books (school libraries, seed)",
      "Open Permits (govtech, Series A)",
    ],
    helpsWith: [
      "RFP and procurement strategy",
      "ESSER and Title-I funding navigation",
      "School-district and city-government intros",
      "Outcome-measurement frameworks",
    ],
    founderQualities: [
      "Mission-driven without being preachy",
      "Realistic about long sales cycles",
      "Has worked inside a district, city, or nonprofit before",
    ],
    websitePlaceholder: "beaconpublic.example",
    tags: ["edtech", "govtech", "social-impact", "k12", "seed", "series-a", "lead"],
  },
  {
    kind: "investor",
    id: "mock-investor-07",
    name: "Tessellate Partners",
    tagline: "Seed-stage AI applications and tooling.",
    investorType: "firm",
    checkRange: "$1M – $4M",
    stages: ["seed"],
    sectors: ["AI", "Developer tools", "B2B SaaS"],
    geography: "Global, English-speaking",
    equityPreference: "Lead or co-lead, 12-18% target ownership",
    thesis:
      "We back applied-AI companies where the moat is product, distribution, or proprietary data — not the model. We help with go-to-market and pricing.",
    portfolio: [
      "Quill & Ledger (fintech, pre-seed)",
      "Echo Voice (AI consumer, seed)",
      "Beacon Trace (security, seed)",
      "Lattice Forge (devtools, seed)",
      "Rangefinder Insights (B2B SaaS, seed)",
    ],
    helpsWith: [
      "Pricing and packaging for AI products",
      "OpenAI and Anthropic enterprise relationships",
      "Recruiting applied-ML and product-design hires",
      "Series A narrative work",
    ],
    founderQualities: [
      "Strong product taste",
      "Has shipped to a customer before, not just a model demo",
      "Clear point of view on the moat",
    ],
    websitePlaceholder: "tessellate.example",
    tags: ["ai", "b2b-saas", "devtools", "seed", "lead", "applied-ai"],
  },
  {
    kind: "investor",
    id: "mock-investor-08",
    name: "Marcus Chen",
    tagline: "Angel for consumer marketplaces and food-and-beverage CPG.",
    investorType: "angel",
    checkRange: "$50K – $200K",
    stages: ["pre_seed", "seed"],
    sectors: ["Consumer", "Marketplace", "Food & Beverage"],
    geography: "North America",
    equityPreference: "Follow",
    thesis:
      "I back consumer-marketplace and CPG founders with strong unit economics and an obsession with the product experience. I prefer brands with a real perspective.",
    portfolio: [
      "Silt & Spark (consumer marketplace, pre-seed)",
      "Larder & Loft (CPG, seed)",
      "Tonn Tackle (DTC, pre-seed)",
      "Flora Bath (CPG, seed)",
      "Quay Foods (marketplace, seed)",
    ],
    helpsWith: [
      "Cold-chain and 3PL operator intros",
      "Whole Foods and specialty-retail buyer relationships",
      "Founder-led-marketing playbooks",
    ],
    founderQualities: [
      "Strong taste and design instincts",
      "Has a real opinion on the customer experience",
      "Numerate on unit economics",
    ],
    websitePlaceholder: "marcus.example",
    tags: ["consumer", "marketplace", "food", "cpg", "angel", "pre-seed", "operator"],
  },
  {
    kind: "investor",
    id: "mock-investor-09",
    name: "Foreland Security Partners",
    tagline: "Series A cyber, compliance, and regulated SaaS.",
    investorType: "firm",
    checkRange: "$5M – $15M",
    stages: ["series_a"],
    sectors: ["Security", "Compliance", "B2B SaaS"],
    geography: "US + Israel",
    equityPreference: "Lead, 15-20% target ownership",
    thesis:
      "We lead cyber Series A rounds where the company has at least three Fortune 500 customers and a clear path to FedRAMP or equivalent.",
    portfolio: [
      "Beacon Trace (security, seed)",
      "Sentinel CSPM (cloud-security, Series A)",
      "Manifold IAM (identity, Series A)",
      "Anvil Compliance (GRC, Series A)",
      "Marlow Backup (resilience, Series B)",
    ],
    helpsWith: [
      "FedRAMP and StateRAMP navigation",
      "CISO advisory-board recruiting",
      "Enterprise pricing and packaging",
      "Series B-narrative work",
    ],
    founderQualities: [
      "Security-domain expertise (founding team or first hires)",
      "Comfort with multi-quarter enterprise sales",
      "Clear plan for distribution beyond CISO friend-and-family",
    ],
    websitePlaceholder: "forelandsecurity.example",
    tags: ["b2b-saas", "security", "compliance", "regulated", "series-a", "lead", "fedramp"],
  },
  {
    kind: "investor",
    id: "mock-investor-10",
    name: "Aishwarya Rao",
    tagline: "Angel for biotech and healthcare-software founders.",
    investorType: "angel",
    checkRange: "$50K – $250K",
    stages: ["seed"],
    sectors: ["Biotech", "Healthcare", "Health IT"],
    geography: "US",
    equityPreference: "Follow or co-invest",
    thesis:
      "I write small checks for biotech and healthcare-software founders working on under-served patient populations. I prefer founders with at least one author-listed clinical publication.",
    portfolio: [
      "Marrow Health (registry, seed)",
      "Tessera Bio (biotech, Series A)",
      "Hyacinth Oncology (biotech, seed)",
      "Vista Mental (clinical software, seed)",
      "Lonsdale Diagnostics (lab software, seed)",
    ],
    helpsWith: [
      "Clinical-advisory-board recruiting",
      "Patient-advocacy-organization intros",
      "FDA and CMS strategic context",
    ],
    founderQualities: [
      "Clinical or scientific co-founder",
      "Realistic about regulatory and reimbursement timelines",
      "Mission-aligned with under-served patients",
    ],
    websitePlaceholder: "aishwarya.example",
    tags: ["biotech", "healthcare", "regulated", "angel", "seed", "operator"],
  },
  {
    kind: "investor",
    id: "mock-investor-11",
    name: "Argonaut Crypto Ventures",
    tagline: "Seed and Series A web3 infrastructure with regulated-rails focus.",
    investorType: "firm",
    checkRange: "$2M – $7M",
    stages: ["seed", "series_a"],
    sectors: ["Web3", "Fintech", "Infrastructure"],
    geography: "Global",
    equityPreference: "Lead or co-lead, 12-18% target ownership",
    thesis:
      "We back web3 infrastructure companies that operate inside a regulatory perimeter. We avoid pure consumer crypto and pure DeFi protocols.",
    portfolio: [
      "Drift Markets (FX, seed)",
      "Onchain Reserves (treasury, Series A)",
      "Chord Custody (institutional custody, Series A)",
      "Rampway (payments, seed)",
      "Indigo Stables (stablecoin, Series A)",
    ],
    helpsWith: [
      "Regulator and broker-dealer intros",
      "Treasury management and OTC desks",
      "Compliance and licensing work-streams",
    ],
    founderQualities: [
      "Capital-markets or regulator experience on the team",
      "Comfortable saying no to crypto-trading-style narratives",
      "Strong compliance hygiene from day one",
    ],
    websitePlaceholder: "argonautcrypto.example",
    tags: ["web3", "fintech", "infrastructure", "regulated", "seed", "series-a", "lead"],
  },
  {
    kind: "investor",
    id: "mock-investor-12",
    name: "Greenshield Frontier Fund",
    tagline: "Seed deeptech across robotics, hardware, and applied physics.",
    investorType: "firm",
    checkRange: "$2M – $6M",
    stages: ["seed"],
    sectors: ["Hardware", "Robotics", "Deeptech"],
    geography: "North America + Europe",
    equityPreference: "Lead or co-lead, 15-20% target ownership",
    thesis:
      "We lead deeptech seed rounds where a credible team is taking lab-validated technology toward a first commercial deployment in 24 months.",
    portfolio: [
      "Northbeam Robotics (warehouses, Series A)",
      "Glyph (hearing aids, seed)",
      "Beacon Bonsai (agtech, seed)",
      "Forge Vehicles (hardware, seed)",
      "Sable Optics (deeptech, Series A)",
    ],
    helpsWith: [
      "Manufacturing-engineering and ops hires",
      "Defence, energy, and industrial customer intros",
      "Capex strategy for hardware companies",
      "Deeptech-style Series A narrative",
    ],
    founderQualities: [
      "Has shipped a hardware product before, even at lab-prototype scale",
      "Comfort with capex and supply-chain reality",
      "Clear plan for first paying customer",
    ],
    websitePlaceholder: "greenshield.example",
    tags: ["hardware", "robotics", "deeptech", "industrial", "seed", "lead"],
  },
];

/**
 * Convenience: return the candidate pool for a given user role. Founders
 * see investors; investors see startups; anything else returns an empty
 * array (the UI handles the empty case with a fallback message).
 */
export function candidatesForRole(
  role: "founder" | "investor" | null | undefined,
): readonly (StartupRecommendation | InvestorRecommendation)[] {
  if (role === "founder") return MOCK_INVESTORS;
  if (role === "investor") return MOCK_STARTUPS;
  return [];
}
