/**
 * lib/matching/learning-model/coefficients.ts
 *
 * LogReg C=2.0 Phase 11c champion model coefficients for production shadow scoring.
 *
 * ─── NOTICE ──────────────────────────────────────────────────────────────────
 * • These coefficients were trained on ENTIRELY SYNTHETIC data.
 * • This model is NOT investment advice.
 * • It does NOT predict startup success or investment returns.
 * • It represents profile-fit and intro-relevance scoring only.
 * • scoreMatch in lib/matching/score.ts remains the production ranker.
 * • Shadow scores computed from these coefficients never change feed ordering.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Provenance:
 *   Generated by: scripts/ml/export_coefficients.py
 *   Training set:  data/synthetic-matching/pairs.json (eligible-only, 260 pairs)
 *   Pipeline:      StandardScaler → LogisticRegression(C=2.0, random_state=42)
 *   Training accuracy (in-sample): 0.9538
 *   OOF accuracy (Phase 11b): 0.8346  ← fairest estimate of generalisation
 *   Per-founder NDCG@5 (5-seed OOF): 0.9882 ± 0.0033
 *   Coefficient JSON: data/synthetic-matching/artifacts/learning_model_coefficients.json
 *
 * Re-export procedure (run when pairs.json or training config changes):
 *   npm run export-coefficients
 *   Paste the printed block over the constants below.
 *   Bump COEFFICIENTS_VERSION (major if FEATURE_ORDER changes; minor for retrain).
 */

export const COEFFICIENTS_VERSION = "11c-logreg-c2.0-1.0.0";

/**
 * Canonical feature order — MUST match FEATURE_COLS in
 * scripts/ml/train_synthetic_matching.py and the vector produced by
 * lib/matching/learning-model/feature-vector.ts.
 * Any reordering is a breaking change: bump COEFFICIENTS_VERSION.
 */
export const FEATURE_ORDER: readonly string[] = [
  "sector_overlap_score",
  "stage_match_score",
  "check_size_score",
  "geography_score",
  "interest_overlap_score",
  "anti_thesis_conflict_score",
  "customer_type_overlap_score",
  "business_model_overlap_score",
  "lead_follow_score",
  "traction_strength_score",
  "profile_completeness_score",
  "semantic_similarity_score",   // null → 0.0 before scaling
];

/** Label class indices [0=poor fit, 1=weak, 2=possible, 3=strong, 4=excellent]. */
export const CLASSES: readonly number[] = [0, 1, 2, 3, 4];

/** StandardScaler feature means (one per feature, in FEATURE_ORDER). */
export const SCALER_MEAN: readonly number[] = [
  0.46474359, 0.78038462, 0.86591575, 0.91230769, 0.19807692, 0.08615385,
  0.85076923, 0.83346154, 0.89846154, 0.50173077, 1.00000000, 0.29553533,
];

/**
 * StandardScaler feature scales = sklearn's `scaler.scale_` (population std,
 * ddof=0).  Used as: scaled = (raw - mean) / scale.
 * Note: this is NOT the same as np.std(X, ddof=1).
 */
export const SCALER_SCALE: readonly number[] = [
  0.37799592, 0.29410857, 0.21795234, 0.23794485, 0.17180085, 0.14607366,
  0.28195639, 0.32509694, 0.12648175, 0.30894810, 1.00000000, 0.10302922,
];

/**
 * LogReg coefficients: shape [5 classes × 12 features].
 * Outer index = class (0–4); inner index = feature (FEATURE_ORDER).
 */
export const COEF: readonly (readonly number[])[] = [
  [-4.69922051, -3.09036713, -2.22714461, -0.56533389, -1.47162147,  3.13697911, -1.74029862, -1.44157948,  0.03461831, -1.10385649,  0.00000000,  0.02773910],
  [-2.31204549, -1.54423537, -1.19370033, -0.88782311, -0.66540367,  1.43302140, -0.80175075, -0.98203224, -0.36501234, -0.98668038,  0.00000000, -0.09842614],
  [ 0.17072999, -0.11671653, -0.43019303, -0.16789836, -0.03808414, -0.06815266,  0.19782356, -0.00126321, -0.03160447, -0.13368556,  0.00000000,  0.14883581],
  [ 2.82700164,  1.68552277,  0.68014983,  0.25571807,  0.53355312, -2.11469259,  1.41488938,  1.09755506, -0.05656276,  0.36235248,  0.00000000,  0.00415551],
  [ 4.01353437,  3.06579626,  3.17088814,  1.36533729,  1.64155616, -2.38715525,  0.92933643,  1.32731987,  0.41856125,  1.86186996,  0.00000000, -0.08230429],
];

/** LogReg intercepts: one per class (0–4). */
export const INTERCEPT: readonly number[] = [
  -3.38972179, 2.72936499, 3.91802753, 0.58918086, -3.84685160,
];
